In [3]:
import osmnx as ox

import numpy as np
import pandas as pd
import geopandas as gpd
import shapely
import h3

pd.set_option("display.max_columns", None)

In [8]:
place_name = "Provincia de Concepción, Chile"

place_string = "_".join(place_name.lower().split(",")[0].split(" "))

In [9]:
blocks_gdf = gpd.read_parquet("blocks/Cartografia_censo2024_Pais_Manzanas.parquet")
blocks_gdf = blocks_gdf[blocks_gdf.PROVINCIA == "CONCEPCIÓN"]
blocks_gdf = blocks_gdf[blocks_gdf.n_per > 0]
blocks_gdf

,OBJECTID,CUT,COD_REGION,REGION,COD_PROVINCIA,PROVINCIA,COMUNA,AREA_C,MANZENT,DISTRITO,COD_DISTRITO,COD_LOCALIDAD,COD_ZONA,LOCALIDAD,COD_ENTIDAD,COD_MANZANA,ENTIDAD,TIPO_MZ,COD_CATEGORIA,CATEGORIA,MZ_BASE_CENSO,ID_ENTIDAD,ID_LOCALIDAD,ID_DISTRITO,ID_ZONA,n_per,n_hombres,n_mujeres,n_edad_0_5,n_edad_6_13,n_edad_14_17,n_edad_18_24,n_edad_25_44,n_edad_45_59,n_edad_60_mas,prom_edad,n_inmigrantes,n_nacionalidad,n_pueblos_orig,n_afrodescendencia,n_lengua_indigena,n_religion,n_dificultad_ver,n_dificultad_oir,n_dificultad_mover,n_dificultad_cogni,n_dificultad_cuidado,n_dificultad_comunic,n_discapacidad,n_estcivcon_casado,n_estcivcon_conviviente,n_estcivcon_conv_civil,n_estcivcon_anul_sep_div,n_estcivcon_viudo,n_estcivcon_soltero,prom_escolaridad18,n_asistencia_parv,n_asistencia_basica,n_asistencia_media,n_asistencia_superior,n_cine_nunca_curso_primera_infancia,n_cine_primaria,n_cine_secundaria,n_cine_terciaria_maestria_doctorado,n_cine_especial_diferencial,n_analfabet,n_ocupado,n_desocupado,n_fuera_fuerza_trabajo,n_cise_rec_independientes,n_cise_rec_dependientes,n_cise_rec_trabajador_no_remunerado,n_ciuo_1,n_ciuo_2,n_ciuo_3,n_ciuo_4,n_ciuo_5,n_ciuo_6,n_ciuo_7,n_ciuo_8,n_ciuo_9,n_ciuo_0,n_caenes_A,n_caenes_B,n_caenes_C,n_caenes_D,n_caenes_E,n_caenes_F,n_caenes_G,n_caenes_H,n_caenes_I,n_caenes_J,n_caenes_K,n_caenes_L,n_caenes_M,n_caenes_N,n_caenes_O,n_caenes_P,n_caenes_Q,n_caenes_R,n_caenes_S,n_caenes_T,n_caenes_U,n_transporte_auto,n_transporte_publico,n_transporte_camina,n_transporte_bicicleta,n_transporte_motocicleta,n_transporte_cab_lan_bote,n_transporte_otros,n_hog,prom_per_hog,n_hog_unipersonales,n_hog_60,n_hog_menores,n_jefatura_mujer,n_tenencia_propia_pagada,n_tenencia_propia_pagandose,n_tenencia_arrendada_contrato,n_tenencia_arrendada_sin_contrato,n_tenencia_cedida_trabajo,n_tenencia_cedida_familiar,n_tenencia_otro,n_comb_cocina_gas,n_comb_cocina_parafina,n_comb_cocina_lena,n_comb_cocina_pellet,n_comb_cocina_carbon,n_comb_cocina_electricidad,n_comb_cocina_solar,n_comb_cocina_no_utiliza,n_comb_calefaccion_gas,n_comb_calefaccion_parafina,n_comb_calefaccion_lena,n_comb_calefaccion_pellet,n_comb_calefaccion_carbon,n_comb_calefaccion_electricidad,n_comb_calefaccion_otra,n_comb_calefaccion_no_utiliza,n_serv_tel_movil,n_serv_compu,n_serv_tablet,n_serv_internet_fija,n_serv_internet_movil,n_serv_internet_satelital,n_internet,n_vp,n_vp_ocupada,n_vp_desocupada,n_tipo_viv_casa,n_tipo_viv_depto,n_tipo_viv_indigena,n_tipo_viv_pieza,n_tipo_viv_mediagua,n_tipo_viv_movil,n_tipo_viv_otro,n_dormitorios_1,n_dormitorios_2,n_dormitorios_3,n_dormitorios_4,n_dormitorios_5,n_dormitorios_6_o_mas,n_viv_hacinadas,n_viv_irrecuperables,n_hog_allegados,n_nucleos_hacinados_allegados,n_viv_no_ampliables,n_deficit_cuantitativo,n_mat_paredes_hormigon,n_mat_paredes_albanileria,n_mat_paredes_tabique_forrado,n_mat_paredes_tabique_sin_forro,n_mat_paredes_artesanal,n_mat_paredes_precarios,n_mat_techo_tejas,n_mat_techo_hormigon,n_mat_techo_zinc,n_mat_techo_fibrocemento,n_mat_techo_fonolita,n_mat_techo_paja,n_mat_techo_precarios,n_mat_techo_sin_cubierta,n_mat_piso_radier_con_revestimiento,n_mat_piso_radier_sin_revestimiento,n_mat_piso_baldosa_cemento,n_mat_piso_capa_cemento,n_mat_piso_tierra,n_fuente_agua_publica,n_fuente_agua_pozo,n_fuente_agua_camion,n_fuente_agua_rio,n_distrib_agua_llave,n_distrib_agua_llave_fuera,n_distrib_agua_acarreo,n_serv_hig_alc_dentro,n_serv_hig_alc_fuera,n_serv_hig_fosa,n_serv_hig_pozo,n_serv_hig_acequia_canal,n_serv_hig_cajon_otro,n_serv_hig_bano_quimico,n_serv_hig_bano_seco,n_serv_hig_no_tiene,n_fuente_elect_publica,n_fuente_elect_diesel,n_fuente_elect_solar,n_fuente_elect_eolica,n_fuente_elect_otro,n_fuente_elect_no_tiene,n_basura_servicios,n_basura_entierra,n_basura_eriazo,n_basura_rio,n_basura_otro,SHAPE_Length,SHAPE_Area,SHAPE
14084,14085,8106,8,BIOBÍO,81,CONCEPCIÓN,LOTA,URBANO,8.106011e+12,LOTA ALTO,1,4,1,LOTA,1,3,LOTA,URBANO,1,Ciudad,1,8.106004e+11,81061004.0,810601.0,810601001.0,136.0,63.0,73.0,19.0,17.0,10.0,13.0,31.0,26.0,20.0,32.8,23.0,22.0,28.0,NaN,8.0,89.0,14.0,4.0,15.0,10.0,3.0,3.0,27.0,29.0,16.0,0.0,6.0,6.0,40.0,10.3,16.0,15.0,9.0,4.0,23.0,52.0,36.0,17.0,8.0,5.0,42.0,12.0,43.0,11.0,30.0,1.0,0.0,3.0,3.0,2.0,12.0,1.0,7.0,1.0,13.0,0.0,2.0,1.0,2.0,0.0,1.0,4.0,7.0,0.0,6.0,0.0,0.0,1.0,1.0,2.0,3.0,3.0,5.0,0.0,2.0,2.0,0.0,8.0,21.0,4.0,1.0,0.0,0.0,5.0,43.0,3.2,12.0,6.0,16.0,22.0,28.0,1.0,0.0,1.0,0.0,5.0,8.0,39.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,27.0,0.0,0.0,10.0,0.0,1.0,43.0,17.0,10.0,24.0,37.0,3.0,39.0,50.0,40.0,10.0,43.0,0.0,0.0,0.0,6.0,0.0,1.0,12.0,9.0,12.0,3.0,1.0,2.0,8.0,1.0,3.0,3.0,0.0,7.0,1.0,6.0,30.0,3.0,0.0,0.0,0.0,0.0,36.0,4.0,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,38.0,2.0,0.0,0.0,39.0,0.0,1.0,26.0,0.0,11.0,0.0,1.0,1.0,0.0,0.0,1.0,39.0,1.0,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.027159,6.099572e-06,"MULTIPOLYGON (((-73.14497 -37.06922, -73.14481..."
14085,14086,8106,8,BIOBÍO,81,CONCEPCIÓN,LOTA,URBANO,8.106011e+12,LOTA ALTO,1,4,1,LOTA,1,4,LOTA,URBANO,1,Ciudad,1,8.106004e+11,81061004.0,810601.0,810601001.0,18.0,8.0,10.0,2.0,2.0,1.0,3.0,5.0,5.0,0.0,29.5,NaN,NaN,NaN,0.0,0.0,13.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,8.0,0.0,0.0,0.0,4.0,10.5,2.0,2.0,1.0,0.0,2.0,8.0,6.0,2.0,0.0,0.0,8.0,2.0,4.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,2.0,5.0,3.6,0.0,0.0,3.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0,5.0,3.0,0.0,5.0,4.0,0.0,5.0,10.0,5.0,5.0,9.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.007011,1.425465e-06,"MULTIPOLYGON (((-73.14802 -37.07193, -73.14806..."
14086,14087,8106,8,BIOBÍO,81,CONCEPCIÓN,LOTA,URBANO,8.106011e+12,LOTA ALTO,1,4,1,LOTA,1,5,LOTA,URBANO,1,Ciudad,1,8.106004e+11,81061004.0,810601.0,810601001.0,65.0,30.0,35.0,10.0,10.0,4.0,4.0,15.0,16.0,6.0,31.5,0.0,0.0,5.0,0.0,0.0,38.0,2.0,2.0,2.0,1.0,0.0,0.0,6.0,18.0,4.0,0.0,5.0,2.0,14.0,11.1,5.0,10.0,4.0,2.0,10.0,26.0,21.0,7.0,1.0,2.0,20.0,8.0,15.0,5.0,15.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,5.0,1.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,8.0,8.0,0.0,0.0,0.0,1.0,23.0,2.8,5.0,3.0,12.0,10.0,16.0,0.0,0.0,1.0,0.0,3.0,3.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,17.0,0.0,0.0,5.0,0.0,0.0,23.0,9.0,1.0,15.0,16.0,0.0,21.0,24.0,23.0,1.0,22.0,0.0,0.0,0.0,2.0,0.0,0.0,8.0,10.0,4.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,0.0,9.0,12.0,2.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,22.0,0.0,0.0,1.0,0.0,22.0,0.0,1.0,0.0,21.0,2.0,0.0,19.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.023824,7.271495e-06,"MULTIPOLYGON (((-73.15977 -37.07338, -73.15986..."
14087,14088,8106,8,BIOBÍO,81,CONCEPCIÓN,LOTA,URBANO,8.106011e+12,LOTA ALTO,1,4,1,LOTA,1,7,LOTA,URBANO,1,Ciudad,1,8.106004e+11,81061004.0,810601.0,810601001.0,118.0,62.0,56.0,11.0,8.0,4.0,11.0,36.0,27.0,21.0,37.9,NaN,0.0,12.0,NaN,4.0,88.0,11.0,5.0,15.0,10.0,2.0,3.0,26.0,22.0,10.0,0.0,10.0,6.0,51.0,9.8,5.0,7.0,4.0,5.0,16.0,55.0,35.0,11.0,1.0,6.0,50.0,7.0,42.0,8.0,41.0,1.0,0.0,2.0,4.0,1.0,5.0,2.0,15.0,3.0,14.0,0.0,6.0,1.0,4.0,1.0,0.0,11.0,9.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,5.0,1.0,3.0,1.0,1.0,0.0,0.0,8.0,24.0,13.0,0.0,0.0,1.0,2.0,39.0,3.0,7.0,4.0,13.0,21.0,33.0,0.0,3.0,1.0,0.0,2.0,0.0,36.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,32.0,0.0,0.0,1.0,0.0,2.0,36.0,18.0,4.0,29.0,29.0,2.0,33.0,52.0,38.0,14.0,49.0,0.0,0.0,0.0,3.0,0.0,0.0,10.0,19.0,4.0,3.0,2.0,0.0,5.0,0.0,1.0,3.0,0.0,4.0,2.0,5.0,29.0,2.0,0.0,0.0,1.0,0.0,35.0,2.0,0.0,0.0,0.0,0.0,36.0,1.0,1.0,0.0,0.0,38.0,0.0,0.0,0.0,38.0,0.0,0.0,35.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,0.0,0.0,0.0,0.0,0.0,38.0,0.0,0.0,0.0,0.0,0.019559,3.664696e-06,"MULTIPOLYGON (((-73.15706 -37.07353, -73.15708..."
14088,14089,8106,8,BIOBÍO,81,CONCEPCIÓN,LOTA,URBANO,8.106011e+12,LOTA ALTO,1,4,1,LOTA,1,8,LOTA,URBANO,1,Ciudad,1,8.106004e+11,81061004.0,810601.0,810601001.0,21.0,13.0,8.0,0.0,2.0,1.0,2.0,3.0,7.0,6.0,44.0,0.0,0.0,9.0,0.0,NaN,13.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,9.0,0.0,0.0,2.0,1.0,7.0,10.6,0.0,2.0,1.0,2.0,0.0,11.0,9.0,1.0,0.0,0.0,11.0,2.0,6.0,1.0,10.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,1.0,8.0,2.6,3.0,4.0,2.0,3.0,4.0,0.0,0.0,0.0,0.0,2.0,2.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,1.0,8.0,2.0,1.0,7.0,7.0,0.0,7.0,11.0,8.0,3.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.003368,3.985827e-07,"MULTIPOLYGON (((-73.14937 -37.07314, -73.14936..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207978,207979,8105,8,BIOBÍO,81,CONCEPCIÓN,HUALQUI,RURAL,8.105093e+12,QUILACOYA,9,41,41,QUILACOYA,73,14,QUILACOYA,ALDEA,3,Aldea,1,8.105020e+05,81052041.0,810509.0,810509041.0,39.0,23.0,16.0,1.0,5.0,3.0,6.0,7.0,9.0,8.0,40.0,0.0,0.0,9.0,0.0,NaN,26.0,2.0,0.0,1.0,1.0,0.0,0.0,4.0,12.0,6.0,0.0,2.0,1.0,11.0,8.9,0.0,5.0,2.0,2.0,1.0,24.0,12.0,2.0,0.0,5.0,12.0,4.0,16.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,2.0,1.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,6.0,3.0,0.0,0.0,0.0,0.0,13.0,3.0,1.0,4.0,5.0,8.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,13.0,2.0,1.0,0.0,10.0,0.0,10.0,16.0,13.0,3.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.003388,6.113251e-07,"MULTIPOLYGON (((-72.95599 -37.05802, -72.95532..."
207979,207980,8105,8,BIOBÍO,81,CONCEPCIÓN,HUALQUI,RURAL,8.105093e+12,QUILACOYA,9,41,41,QUILACOYA,73,15,QUILACOYA,ALDEA,3,Aldea,1,8.105020e+05,81052041.0,810509.0,810509041.0,41.0,19.0,22.0,2.0,3.0,4.0,6.0,12.0,9.0,5.0,35.7,0.0,0.0,6.0,0.0,NaN,25.0,1.0,1.0,2.0,0.0,0.0,0.0,3.0,12.0,6.0,0.0,3.0,1.0,13.0,10.8,1.0,3.0,4.0,3.0,3.0,17.0,15.0,5.0,1.0,2.0,18.0,2.0,15.0,6.0,12.0,0.0,0.0,2.0,0.0,0.0,7.0,1.0,4.0,1.0,3.0,0.0,3.0,0.0,3.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,2.0,10.0,1.0,0.0,0.0,0.0,4.0,13.0,3.2,1.0,1.0,4.0,4.0,9.0,0.0,2.0,0.0,0.0,1.0,1.0,9.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10.0,0.0,0.0,2.0,0.0,0.0,13.0,7.0,4.0,2.0,13.0,0.0,13.0,21.0,16.0,5.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,11.0,0.0,0.0,1.0,1.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,13.0,0.0,0.0,1.0,0.0,11.0,1.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.005617,1.309680e-06,"MULTIPOLYGON (((-72.96239 -37.05854, -72.96188..."
207980,207981,8105,8,BIOBÍO,81,CONCEPCIÓN,HUALQUI,RURAL,8.105093e+12,QUILACOYA,9,41,41,QUILACOYA,73,16,QUILACOYA,ALDEA,3,Aldea,1,8.105020e+05,81052041.0,810509.0,810509041.0,23.0,10.0,13.0,1.0,3.0,0.0,5.0,4.0,6.0,4.0,38.1,0.0,0.0,NaN,0.0,NaN,11.0,0.0,0.0,2.0,2.0,1.0,1.0,3.0,4.0,4.0,0.0,1.0,2.0,8.0,8.8,1.0,2.0,0.0,2.0,2.0,14.0,6.0,1.0,0.0,2.0,8.0,2.0,9.0,0.0,8.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,2.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,1.0,7.0,3.3,0.0,1.0,2.0,3.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,2.0,7.0,3.0,0.0,0.0,5.0,0.0,5.0,7.0,7.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.002857,4.917914e-07,"MULTIPOLYGON (((-72.95637 -37.05836, -72.95634..."
207981,207982,8105,8,BIOBÍO,81,CONCEPCIÓN,HUALQUI,RURAL,8.105093e+12,QUILACOYA,9,41,41,QUILACOYA,73,17,QUILACOYA,ALDEA,3,Aldea,1,8.105020e+05,81052041.0,810509.0,810509041.0,12.0,4.0,8.0,0.0,2.0,1.0,2.0,2.0,4.0,1.0,36.8,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,6.0,0.0,0.0,0.0,4.0,9.4,0.0,2.0,0.0,0.0,0.0,7.0,4.0,1.0,0.0,1.0,8.0,0.0,2.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,0.0,0.0,0.0,1.0,4.0,3.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,0.0,0.0,3.0,0.0,3.0,4.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.003521,2.724976e-07,"MULTIPOLYGON (((-72.95471 -37.0582, -72.95484 ..."
207982,207983,8105,8,BIOBÍO,81,CONCEPCIÓN,HUALQUI,RURAL,8.105093e+12,QUILACOYA,9,41,41,QUILACOYA,73,1,QUILACOYA,ALDEA,3,Aldea,1,8.105020e+05,81052041.0,810509.0,810509041.0,7.0,5.0,2.0,0.0,1.0,0.0,0.0,2.0,2.0,2.0,49.1,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,11.5,0.0,1.0,0.0,0.0,0.0,3.0,1.0,3.0,0.0,0.0,4.0,0.0,2.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,1.4,3.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,5.0,4.0,0.0,2.0,4.0,0.0,4.0,5.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,5.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,2.0,0.0,5.0,0.0,0.0,0.0,0.0,0.017988,3.209946e-06,"MULTIPOLYGON (((-72.96273 -37.05866, -72.96273..."

In [10]:
# generate the point grid

# point resolution (insert the spacing in meters below)
spacing = 100

# project to UTM to improve the location of points
bounds = blocks_gdf.to_crs(32718).total_bounds

# sample coordinates along x and y axis with numpy arange
points_x = np.arange(bounds[0], bounds[2], spacing)
points_y = np.arange(bounds[1], bounds[3], spacing)

# create points with the coordinates paired as tuples
points = shapely.points([(x, y) for x in points_x for y in points_y])

# create the points_gdf from the points
points_gdf = gpd.GeoDataFrame(geometry=points, crs=32718)
points_gdf = points_gdf.to_crs(4326)

# intersect with the city blocks with actual people living there (n_per > 0)
# match_indices = points_gdf.sindex.query(area, predicate="intersects")
match_indices = points_gdf.sindex.query(blocks_gdf.geometry, predicate="intersects")
points_gdf = points_gdf.iloc[match_indices[1]]
points_gdf = points_gdf.reset_index()

# create x, y columns for standarization purposes only
points_gdf["x"] = points_gdf.geometry.x
points_gdf["y"] = points_gdf.geometry.y
points_gdf = points_gdf[["x", "y", "geometry"]]

points_gdf

               x          y                     geometry
0     -73.148737 -37.074846  POINT (-73.14874 -37.07485)
1     -73.148759 -37.073946  POINT (-73.14876 -37.07395)
2     -73.146576 -37.071208  POINT (-73.14658 -37.07121)
3     -73.145474 -37.070289  POINT (-73.14547 -37.07029)
4     -73.145496 -37.069388   POINT (-73.1455 -37.06939)
...          ...        ...                          ...
19119 -72.961385 -37.056452  POINT (-72.96138 -37.05645)
19120 -72.961360 -37.057352  POINT (-72.96136 -37.05735)
19121 -72.955716 -37.058157  POINT (-72.95572 -37.05816)
19122 -72.962460 -37.058273  POINT (-72.96246 -37.05827)
19123 -72.955692 -37.059057  POINT (-72.95569 -37.05906)

[19124 rows x 3 columns]

In [11]:
points_gdf.to_parquet(f"points/points_{place_string}.parquet")

In [14]:
# get all the h3 hexagons from all the points generated
# (which already are inside blocks with people)

cells = points_gdf.apply(lambda p: h3.latlng_to_cell(p.y, p.x, 9), 1)
cells = cells.drop_duplicates()

hexagons = [h3.cell_to_boundary(cell) for cell in cells]

# invert coordinates as h3.cell_to_boundary returns points with
# their coordinates flipped for some reason (?)
hexagons = [[(c[1], c[0]) for c in g] for g in hexagons]

# create the polygons
polygons = shapely.polygons(hexagons)

# create the hexagons_gdf with those polygons
hexagons_gdf = gpd.GeoDataFrame({"cell": cells}, geometry=polygons, crs=4326)

hexagons_gdf

                  cell                                           geometry
0      89b2dbca64bffff  POLYGON ((-73.14735 -37.07629, -73.1466 -37.07...
2      89b2dbca653ffff  POLYGON ((-73.14509 -37.07174, -73.14434 -37.0...
5      89b2dbca65bffff  POLYGON ((-73.14785 -37.07332, -73.1471 -37.07...
7      89b2dbcb5d7ffff  POLYGON ((-73.15937 -37.07666, -73.15862 -37.0...
8      89b2dbcb5d3ffff  POLYGON ((-73.16262 -37.07528, -73.16187 -37.0...
...                ...                                                ...
19097  89b2dbc2a5bffff  POLYGON ((-72.96065 -37.05685, -72.9599 -37.05...
19100  89b2dbc2a7bffff  POLYGON ((-72.95365 -37.06258, -72.9529 -37.06...
19101  89b2dbc2a4fffff  POLYGON ((-72.95689 -37.0612, -72.95615 -37.05...
19108  89b2dbc2a47ffff  POLYGON ((-72.95415 -37.05962, -72.95341 -37.0...
19114  89b2dbc2a4bffff  POLYGON ((-72.96014 -37.05981, -72.9594 -37.05...

[3108 rows x 2 columns]

In [15]:
hexagons_gdf.to_parquet(f"hexagons/hexagons_{place_string}.parquet")